### ISSUE TITLE
RUCSS - allow to safelist @font-face rules

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#3963]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

Currently, the RUCSS safelist will accept CSS ids/classes/files. 

It's impossible to safelist `@font-face` rules like the following:
```CSS
@font-face{font-family:eicons;src:url(https://example.com/wp-content/plugins/elementor/assets/lib/eicons/fonts/eicons.eot?5.10.0);src:url(https://example.com/wp-content/plugins/elementor/assets/lib/eicons/fonts/eicons.eot?5.10.0#iefix) format("embedded-opentype"),url(https://example.com/wp-content/plugins/elementor/assets/lib/eicons/fonts/eicons.woff2?5.10.0) format("woff2"),url(https://example.com/wp-content/plugins/elementor/assets/lib/eicons/fonts/eicons.woff?5.10.0) format("woff"),url(https://example.com/wp-content/plugins/elementor/assets/lib/eicons/fonts/eicons.ttf?5.10.0) format("truetype"),url(https://example.com/wp-content/plugins/elementor/assets/lib/eicons/fonts/eicons.svg?5.10.0#eicon) format("svg");font-weight:400;font-style:normal}
```

This may result in fonts not being loaded on the front-end if that part of CSS is not added in the used CSS by the SaaS.

**To Reproduce**

Not relevant in this case.

**Expected behavior**

There should be a way to safelist `@font-face` rules.

**Screenshots**

**Additional context**

**Slack convo:** https://wp-media.slack.com/archives/C08N8J6VC/p1622185641187300?thread_ts=1622152050.184400&cid=C08N8J6VC

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort
