### ISSUE TITLE
RUCSS - box-shadow is stripped if rgb values are not separated with commas

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#4084]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅ `3.9.0.3`
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

The SaaS will strip the `box-shadow` rule if it's formatted like so:
```CSS
.golin-content {background: #f0f4f8; box-shadow: 0px 0px 15px 0px rgb(197 202 208) inset;}
```
The previous will work fine in a browser.

The following rewrite of the CSS rule works:
```CSS
.golin-content {background: #f0f4f8; box-shadow: inset 0 0 15px 0 rgb(197, 202, 208);}
```

This is coming from the [PHP CSS Parser](https://github.com/sabberworm/PHP-CSS-Parser/) library we are using on the SaaS.

**To Reproduce**

1. Add the following CSS in a file: `.golin-content {background: #f0f4f8; box-shadow: 0px 0px 15px 0px rgb(197 202 208) inset;}`
2. Safe list the `.golin-content` class.
3. Check if that's added in the `wpr-usedcss` block.

**Expected behavior**

The parser should be able to take into consideration CSS rules that are written in a non-standard way.

**Additional context**

I added this here, following @Tabrisrp 's suggestion:
https://wp-media.slack.com/archives/C43T1AYMQ/p1624363779364500

I'll also post this in the library's GitHub repo.

Related ticket: https://secure.helpscout.net/conversation/1522954655/266523?folderId=273766

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort
