### ISSUE TITLE
RUCSS - calc() included in rgb() isn't being parsed

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#4125]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅3.9.0.4
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

When using CSS `calc()` inside an `rgb()` that will not be parsed.

For example, the following code:
```CSS
.dark{
    background: var(--dark);
    --red: 37;
    --green: 211;
    --blue: 102;
    --dark:rgb( calc( var(--red) - 75),calc( var(--green) - 75),calc( var(--blue) - 75));
}
```
becomes:
```CSS
.dark{background:var(--dark);--red:37;--green:211;--blue:102}
```

and that results in the `--dark` property being undefined: 
![](https://i.vgy.me/nrk77m.gif)

**To Reproduce**

1. Insert the CSS code I provided earlier in a `<style>` block and assign the class to an element, e.g. a `p`.
2. Safelist the `.dark` class.
3. Check the cached page which won't have the `dark` class applied.

**Expected behavior**

`calc()` inside `rgb()` should be parsed.

**Additional context**

**Related ticket:** https://secure.helpscout.net/conversation/1555907859/275064?folderId=2135277
**Slack discussion:** https://wp-media.slack.com/archives/C43T1AYMQ/p1625146006422800

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort
