### ISSUE TITLE
RUCSS - <svg> elements are removed from the used CSS when that's inserted to a page

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#4474]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅ `3.10.2`
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

When `<svg>` elements are included in the used CSS, e.g. as part of the `background-image` `url`:
```CSS
#ub_styled_list li::before{top:3px;font-size:1em;height:1.1em;width:1.1em;background-image:url("data:image/svg+xml;utf8,<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 512 512\"><path fill=\"%238ed1fc\" d=\"M507.73 109.1c-2.24-9.03-13.54-12.09-20.12-5.51l-74.36 74.36-67.88-11.31-11.31-67.88 74.36-74.36c6.62-6.62 3.43-17.9-5.66-20.16-47.38-11.74-99.55.91-136.58 37.93-39.64 39.64-50.55 97.1-34.05 147.2L18.74 402.76c-24.99 24.99-24.99 65.51 0 90.5 24.99 24.99 65.51 24.99 90.5 0l213.21-213.21c50.12 16.71 107.47 5.68 147.37-34.22 37.07-37.07 49.7-89.32 37.91-136.73zM64 472c-13.25 0-24-10.75-24-24 0-13.26 10.75-24 24-24s24 10.74 24 24c0 13.25-10.75 24-24 24z\"></path></svg>")}
```

those are stripped from the used CSS that's added to the page when that's processed by the `wp_strip_all_tags()` function:
https://github.com/wp-media/wp-rocket/blob/d467569bd73e82989cc87e7dbf1f4ac1f362a7ee/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php#L606

The previous CSS becomes:
```CSS
#ub_styled_list li::before{top:3px;font-size:1em;height:1.1em;width:1.1em;background-image:url("data:image/svg+xml;utf8,")}
```
These results in broken elements.

Note that the used CSS is properly produced by the SaaS and is saved correctly in the database.

**To Reproduce**
1. Pass the CSS code I referenced to `wp_strip_all_tags()`.

**Expected behavior**

`<svg>`s should be preserved in the used CSS.

We can create our own version of `wp_strip_all_tags()` where we can pass the tags we'd like to preserve in `strip_tags()`.

**Additional context**

**Ticket:** https://secure.helpscout.net/conversation/1680359707/304712/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort
