### ISSUE TITLE
Double colon used with single colon on the same selector prevents the lazyloaded background image from being displayed

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#6162]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version :heavy_check_mark: `3.15.0.1`
- Used the search feature to ensure that the bug hasn’t been reported before :heavy_check_mark: 

**Describe the bug**
When CSS like the following is used:
```CSS
input[type="file"]::file-selector-button {
            border: 2px solid #6c5ce7;
            padding: 0.2em 0.4em;
            border-radius: 0.2em;
            background-color: #a29bfe;
            transition: 1s;
}
input[type="file"]::file-selector-button:hover {
            background-image: url(/wp-content/uploads/2023/09/example.png);
            border: 2px solid #00cec9;
}
```

The `example.png` image is _NOT_ displayed on `:hover`.

In `rocket_pairs` we add the following:
```JSON
{
                "selector": "input[type=\"file\"]",
                "style": ":root{--wpr-bg-d70664eb-2e91-49f8-adad-271a08f9a6ef: url('\/wp-content\/uploads\/2023\/09\/example.png');}"
 }
```

but that's not added to `<style id="wpr-lazyload-bg"></style>`

**To Reproduce**
1. Use the CSS provided previously (using a real image) with the following markup:
```HTML
<form>
    <label for="fileUpload">Upload file</label>
    <input type="file" id="fileUpload" />
</form>
```
2. Hover over the "Upload file" button.
3. The background image is not loaded.

The following template can be used as well:
https://github.com/wp-media/rocket-test-data/blob/e07b3e650a8dcd0f4ad08fd3b9fcbe0c63d1bc39/templates/ll_bg_css_double_colon.php

**Expected behavior**

The background image should be displayed.

**Screenshots**

N/A

**Additional context**

Props to @Mai-Saad for finding that using `::` and `:` is possible.

**Acceptance Criteria (for WP Media team use only)**
1. The image added using double and single colon in CSS should be lazyloaded correctly
2. We should not introduce regression compared to the previous state. The templates that could be used for e2e tests are available [here](https://github.com/wp-media/rocket-test-data/blob/master/templates/ll_bg_css_single_colon.php) and [here](https://github.com/wp-media/rocket-test-data/blob/master/templates/ll_bg_css_double_colon.php).
