### ISSUE TITLE
LCP is detected with wrong href coming from a url(xxx) syntax

### ISSUE THREAD

**Issue by MathieuLamiot** [wp-media/wp-rocket#6647]
Task submitted by willy837 through TBTT.

**Description of the issue:**
Our Partner Eroan Boyer was attending the meetup last night and reported an issue with Optimize critical images that I was able to replicate on my test site (https://wpr.willychataigner.com/agencewebperformance) by cloning the hp of his site (https://agencewebperformance.fr/).
Issue is 3 links preload are added but the source is incorrect as shown in the source code (https://jmp.sh/uwBwQsyn) and SQL Buddy (https://jmp.sh/kZbA4Yn0).

**Investigation performed:**
I replicated the issue on my test site

**How to reproduce:**
I used the template provided in the thread https://wp-media.slack.com/archives/C072P5EU5DF/p1715965146682579?thread_ts=1715929769.448289&cid=C072P5EU5DF

Helpscout link:n/a
Slack link:https://wp-media.slack.com/archives/C072P5EU5DF/p1715929769448289

**Comment by MathieuLamiot** [comment]
See the Slack thread for details.
In the reported page, the element causing the issue seems to be `gb-container gb-container-4a3de19a blour`

**Comment by Miraeld** [comment]
Ummm I don't have a solution yet, 

But just writing down what I found at the moment might help me or someone else in the future for this grooming. 

Like @MathieuLamiot mentioned, the issue is coming from the `<div class="gb-container gb-container-4a3de19a blour">` and more specifically the `blour` class. 

This class has a css `background-image` which is a SVG, and this SVG is causing trouble to our script. 

Have a look: 

``` css
.blour {
    background-image: url(data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1600 1100"><defs><linearGradient id="a" gradientUnits="userSpaceOnUse" x1="265.75" y1="-174.21" x2="266.45" y2="-173.69" gradientTransform="matrix(-273.52 23.88 -24.5 -280.6 68922.98 -54450.95)"><stop offset="0" stop-color="%2304efcc" stop-opacity="0"></stop><stop offset=".59" stop-color="%2318dbfe" stop-opacity=".75"></stop><stop offset="1" stop-color="%2315f"></stop></linearGradient><filter id="c"><feGaussianBlur in="SourceGraphic" stdDeviation="40"/></filter></defs><g filter="url(%23c)"><path d="M609.2 834c-14.8 12.2-33.2 15.2-50.9 18l-63.2 9.9c-22.6 3.5-46 7-68-.4-34.1-11.5-59.5-48.2-70.8-88.8-11.4-40.6-10.5-84.7-6.3-127.3 1.7-17 4.6-35.5 15.4-46.4 10.6-10.6 25.9-10.9 39.2-6.8 30.4 9.4 54.1 37.6 81.9 55.2 40.7 25.7 93.1 31.2 120.5 75.9 19.7 32 36.6 82.5 2.2 110.7" fill="url(%23a)"></path><linearGradient id="b" gradientUnits="userSpaceOnUse" x1="264.32" y1="-175.76" x2="263.23" y2="-176.43" gradientTransform="matrix(784.51 -166.9 168.95 794.17 -176197.6 184322.88)"><stop offset="0" stop-color="%2304efcc" stop-opacity="0"></stop><stop offset=".48" stop-color="%2318dbfe" stop-opacity=".75"></stop><stop offset="1" stop-color="%2315f"></stop></linearGradient><path d="M653.3 317.7c39.2-41.6 91.7-58.4 142.2-74.1l180.1-55.8c64.5-20 131.2-40.2 197-28.2 102 18.5 186.4 113.9 231.2 226.5 44.8 112.6 55.3 240.7 55.6 365.7.2 49.9-2.8 104.7-31.1 141-27.5 35.3-71.9 42.8-111.6 36.7-90.8-14-167.7-85.4-253.4-124.3-125.3-56.9-278.7-50.2-371-167.5-66.5-84.6-130.3-223.3-39-320" fill="url(%23b)"></path></g></svg>);
    background-repeat: no-repeat;
    background-size: 1200px;
    background-position: -250px top;
}
```

So, our script is picking the `<div>` element, and processing any related `background-image` and of course it found that one. 

However, as we can see, there are no proper URL for an image. However, we can find a patter, which is the same as what we are looking for: 
`fill="url(%23a)"`, `<g filter="url(%23c)">` & `fill="url(%23b)"`. Unfortunately we are matching these. 
With the sanitize function, we get `url(a)`, `url(b)` & `url(c)` which is resulting in the DB as `a/b/c` to be saved as LCP. 

I think we need to rework the lcp-beacon if we want to handle this case, but not sure how...
