### ISSUE TITLE
Lazyload CSS Background Images triggers DOMException errors with specific selector

### ISSUE THREAD

**Issue by sandyfzu** [wp-media/wp-rocket#6654]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅ (3.16)
- Used the search feature to ensure that the bug hasn’t been reported before ✅ (Related but different selector: https://github.com/wp-media/wp-rocket/issues/6199)

**Describe the bug**
When Lazyload for CSS Background Images tries to process CSS like this:

```css
            .bofy-ul-balloon-bullets > div:nth-of-type(7n+1) {
                background: url("http://wp-rocket.esy.es/wp-content/uploads/2020/10/bee-5618012_1920-1024x683.jpg");
            }
            .bofy-ul-balloon-bullets > div:nth-of-type(2n+2) {
                background: url("http://wp-rocket.esy.es/wp-content/uploads/2020/10/tram-5621647_1920-683x1024.jpg");
            }
```
Selector: `.bofy-ul-balloon-bullets > div:nth-of-type(7n+1)`

The following error appears in the console and the images are not loaded:

`Uncaught DOMException: Failed to execute 'querySelectorAll' on 'Document': '1)' is not a valid selector.`

**Expected behavior**
This error shouldn't happen when Lazyload CSS Background is active

**Screenshots**
![image](https://github.com/wp-media/wp-rocket/assets/13713107/6ffd541f-cfca-4b0e-b165-eb4c56745e36)

**Additional context**

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming
