### ISSUE TITLE
CSS Minification Removes Space in :nth-child(of <selector>), Causing Invalid CSS

### ISSUE THREAD

**Issue by rosamillan** [wp-media/wp-rocket#7363]
**Describe the bug**
When using the :nth-child(of <selector>) syntax, Rocket’s minification removes the space before "of," resulting in invalid CSS and layout issues. This appears to be a bug, as the minifier does not yet account for this newer selector.

Reference: [Chrome Docs - :nth-child(of <selector>)](https://developer.chrome.com/docs/css-ui/css-nth-child-of-s)

**To Reproduce**
1. Uses the nth-child(of <selector>) syntax
2. Activate the Minify CSS file
3. See the issue

**Expected behavior**
Minify CSS file feature can recognize the :nth-child(of <selector>) and not modify the syntax.

**Screenshots**

- CSS before being minified- Screenshot: https://jmp.sh/aSiZgcpb
Full file: https://smartbiking.be/wp-content/themes/uncode-child/dist/main.css
- CSS after the Minify CSS file feature is activated- Screenshot: https://jmp.sh/I3L7oEu7
Minified version: https://goonlinetools.com/snapshot/code/#alpkr50sg867fj80wt8fkx

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser Chrome
 - Version Versión 134.0.6998.166 

**Additional context**
HS tickets: https://secure.helpscout.net/conversation/2894226259/550190?viewId=7406897

**Comment by Presskopp** [comment]
I reported this upstream, see https://github.com/matthiasmullie/minify/issues/441

**Comment by KaiNieLC** [comment]
Can confirm this is still an active issue as of WP Rocket 3.23.2.2 (RUCSS/Remove Unused CSS feature). We hit it on a Kadence Blocks site using the "reverse stacking order" option, which generates the following (valid) rules for the mobile/tablet breakpoints:

```css
.kb-row-layout-id...>.kt-row-column-wrap>.wp-block-kadence-column:nth-child(1 of *:not(style)){order:2}
.kb-row-layout-id...>.kt-row-column-wrap>.wp-block-kadence-column:nth-child(2 of *:not(style)){order:1}
```

After RUCSS generates the Used CSS, these become:

```css
.kb-row-layout-id...>.kt-row-column-wrap>.wp-block-kadence-column:nth-child(1of:not(style)){order:2}
.kb-row-layout-id...>.kt-row-column-wrap>.wp-block-kadence-column:nth-child(2of:not(style)){order:1}
```

Both the space before `of` and the `*` are stripped, producing an invalid selector. Since the whole declaration block is then dropped by the browser, the column order defined for mobile is silently lost — in our case this meant a background image ended up rendering below a heading it's supposed to precede, only on mobile/tablet viewports, with desktop unaffected (no reverse-order rule applies there).

Confirmed this is RUCSS-specific by comparing against `?nowprocket=1`, where the selector is intact and the layout is correct.

Worked around it for now with a duplicate, minifier-safe override rule using plain class selectors (`order:-1` on the specific columns), since the broken rule doesn't get regenerated correctly even after a full RUCSS cache clear (confirmed the bug persists after Used CSS regeneration, not just a stale-cache artifact).

Given [matthiasmullie/minify#441](https://github.com/matthiasmullie/minify/issues/441) has also been open for a year with no fix, would it be feasible for WP Rocket's minifier to special-case/skip `:nth-child(... of ...)` selectors (leave that rule unminified) as a stopgap until the upstream library is fixed? Right now this silently breaks layouts for anyone using this fairly common modern CSS pattern (Kadence Blocks generates it whenever "reverse order" is used on responsive columns), and it's likely affecting more sites than have found their way to this issue.
