### ISSUE TITLE
CSS minify/compression bad syntax with flex

### ISSUE THREAD

**Issue by nicomollet** [wp-media/wp-rocket#737]
Hello

On my website https://www.restaurant-caphorn.fr/ I enabled WP Rocket with "CSS Minify/Combine" enabled.

I have a rule in my CSS for the logo alignment
```css
#site-header.medium-header .top-col.logo-col{
    -webkit-flex: auto 0 0;
    flex: auto 0 0;
}
```

which once minified/compressed and is becoming:
```css
#site-header.medium-header .top-col.logo-col {
    -webkit-flex: auto 0 0%;
    flex: auto 0 0%;
}
```

`flex: auto 0 0%;` is not valid CSS, so it breaks the effect I wanted to do. I overrided the rule on my website to fix it, but there is a bug related to WP Rocket or Minify?

Thank you.
Nico
