### ISSUE TITLE
“Cut off” asset URLs in generated files (minify, busting) on virtual host

### ISSUE THREAD

**Issue by glueckpress** [wp-media/wp-rocket#787]
On a virtual host environment, I got a lot of these “cut off” URLs in CSS files generated by WP Rocket (simplified for brevity):

```css
@font-face {
font-family: 'Some-Font';
src: url('te.example.com/wp-content/path/to/font.woff2');
}
```

Instead, it should have been this:

```css
@font-face {
font-family: 'Some-Font';
src: url( 'https://wesite.example.com/wp-content/path/to/font.woff2' );
}
```

Turns out, this is the problem:

https://github.com/wp-media/wp-rocket/blob/2bc483d9a088adddcf5b9a2983bf2c476a8283a4/inc/vendors/classes/class-minify-css-urirewriter.php#L48

`$_SERVER['DOCUMENT_ROOT']` is unreliable here, since it is not always identical with WordPress’ `ABSPATH`. 

This can result in wrong substrings when absolute URLs get re-assembled from path fragments:

https://github.com/wp-media/wp-rocket/blob/2bc483d9a088adddcf5b9a2983bf2c476a8283a4/inc/vendors/classes/class-minify-css-urirewriter.php#L174

## Example:

* `$_SERVER['DOCUMENT_ROOT']` returns `/var/www/virtual/example/html`
* `ABSPATH` returns `'/var/www/virtual/example/website.example.com`

What we need to end up with is a path fragment starting with `/wp-content/`, which then can be used to re-assemble the URL. 

So trimming `$_SERVER['DOCUMENT_ROOT']` from the beginning of a path won’t when it isn’t identical with `ABSPATH`.

## Solution
Replacing the server variable with WordPress’ constant in [/inc/vendors/classes/class-minify-css-urirewriter.php#L48](https://github.com/wp-media/wp-rocket/blob/2bc483d9a088adddcf5b9a2983bf2c476a8283a4/inc/vendors/classes/class-minify-css-urirewriter.php#L48) did the trick:

```php
$docRoot ? $docRoot : ABSPATH
```
