### ISSUE TITLE
Untranslatable on/off sliding checkbox

### ISSUE THREAD

**Issue by Tabrisrp** [wp-media/wp-rocket#906]
With the current implementation, the on/off sliding checkboxes can't be translated, as the text is located in css pseudo-elements.

The question now is: should they be translatable? This could cause design issues depending on the language used.

The other question is: should we have text on those sliding checkboxes? Should we rely on button position and color only to indicate the state of the option?

**Comment by GeekPress** [comment]
Everybody in the world understand and know what "on/off" means. It doesn't need to be translated in my opinion.

For the second question, @edenpulse must be in the part of the discussion. As if it has been designed like that, it was for a specific UX reason.

**Comment by Tabrisrp** [comment]
> Everybody in the world understand and know what "on/off" means.

This is quite a bold statement, and a reductive view of the world. I disagree with it, and I opened this because we had this specific feedback in a ticket, so it's a concern for others too.

But let's focus on the second question and see where we go from there.

**Comment by glueckpress** [comment]
There’s a pretty straightforward solution to this pattern unless I’m mistaken. (Line breaks on HTML element for better readability.)

```php
<input type="checkbox" 
  data-l10n-active="<?php echo esc_attr_x( 'On', 'Active state of checkbox' 'rocket'); ?>" 
  data-l10n-inactive="<?php echo esc_attr_x( 'Off', 'Inactive state of checkbox' 'rocket'); ?>"
>
```

```scss
// OFF text
[type="checkbox"]:not(:checked) + label .wpr-radio-ui:before {
	content: attr(data-l10n-inactive);
	// etc
}

// ON text
[type="checkbox"]:checked + label .wpr-radio-ui:after {
	content: attr(data-l10n-active);
	// ect
}
```
