### ISSUE TITLE
Support multi-line menu descriptions in admin CSS

### ISSUE THREAD

**Issue by glueckpress** [wp-media/wp-rocket#912]
It’s not always possible to come up with translations that fit in the layout. In those cases, basic support for multi-line menu descriptions should be applied.

Current state of multi-line description:

![](https://user-images.githubusercontent.com/308422/38016257-c654fe38-326e-11e8-9627-fc40157ed0ca.png)

This can be fixed by applying a `padding-right` value that considers the icon’s position and dimension:

```css
.wpr-menuItem-title,
.wpr-menuItem-description {
padding-right: 2rem; /* icon font-size (1.625rem) + minimal buffer */
}
```

Result: 

![](https://user-images.githubusercontent.com/308422/38016575-b9444e82-326f-11e8-854d-e9ec44304b3f.png)

There usually is no way to make a realistic assumption about if and where line breaks may occur in other languages. So assumed string lengths should be treated generously.

_Note: The code above hasn’t been tested on different break-points._
